"""Initial Migration

Revision ID: c854cbf7a6d3
Revises: a829adee5c86
Create Date: 2021-06-19 22:50:18.089969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c854cbf7a6d3'
down_revision = 'a829adee5c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_column('user', 'pass_secure')
    # ### end Alembic commands ###
